FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . .

COPY C:\dev\Origination\build\bin\deployNetCore\Origination.Snowman.Core\ .

RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/core/runtime:3.1
WORKDIR /app
COPY --from=build /app .

# EXPOSE 1600

ENTRYPOINT ["./dotnetapp"]


LABEL maintainer="Better Life Group"
