# https://hub.docker.com/_/registry
# docker-compose -f docker-compose.yml up --force-recreate --build -d
# docker-compose -f docker-compose.yml down

version: "3.6"

services:
  #Registry
  registry:
    container_name: docker-registry
    image: registry:latest
    restart: unless-stopped
    ports:
      - "5999:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.passwd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - c:\dkr\registry:/var/lib/registry
    networks:
      - mynet
  
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "85:80"
    volumes:
      - c:\dkr\nginx\conf.d\:/etc/nginx/conf.d/
      - c:\dkr\nginx\ssl\:/etc/nginx/ssl/
    networks:
      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge
