# docker-compose -f influxdb-docker-compose.yml up --force-recreate --build -d
# docker-compose -f influxdb-docker-compose.yml down

version: "3"

services:
  influxdb:
    image: influxdb:2.0-alpine
    container_name: influxdb_2a
    hostname: influxdb
    restart: unless-stopped
    ports:
      - ${INFLUXDB_PORT}:8086
    volumes:
      - ${INFLUXDB_DATA_DIR}:/var/lib/influxdb
      - ${INFLUXDB_DATA2_DIR}:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION}
      